<div class="menu" align="left"> <b><a href="/"><i>SDCC Home</i></a></b>
  <div class="submenu">
    <a href="/index.php#News"><i>News</i></a><br />
    <a href="/index.php#Platforms"><i>Platforms</i></a><br />
    <a href="/index.php#Download"><i>Download</i></a><br />
    <a href="/index.php#Support"><i>Support</i></a><br />
    <a href="/index.php#Who"><i>Who</i></a><br />
  </div>
  <br />
  <b><a href="/snap.php"><i>Snapshots</i></a></b>
  <div class="submenu">
    <a href="/snap.php#Linux"><i>Linux</i></a><br />
    <a href="/snap.php#Windows"><i>Windows</i></a><br />
    <a href="/snap.php#MacOSX"><i>Mac OS X</i></a><br />
    <a href="/snap.php#Docs"><i>Documentation</i></a><br />
    <a href="/snap.php#Source"><i>Source</i></a><br />
  </div>
  <br />
  <b><i>Documentation</i></b>
  <div class="submenu">
    <a href="/doc/sdccman.pdf"><i>SDCC Manual (pdf)</i></a><br />
  </div>
  <br />
  <b><a href="http://sourceforge.net/projects/sdcc"><i>SDCC at SourceForge</i></a></b>
  <div class="submenu">
    <a href="http://sourceforge.net/project/showfiles.php?group_id=599"><i>File releases</i></a><br />
    <a href="https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/"><i>svn repository</i></a><br />
    <a href="https://sourceforge.net/p/sdcc/git-mirror/ci/trunk/tree/"><i>git mirror</i></a><br />
    <a href="https://sourceforge.net/p/sdcc/mailman/"><i>Mailing lists</i></a><br />
    <a href="https://sourceforge.net/p/sdcc/_list/tickets"><i>Issue trackers</i></a><br />
    <a href="https://sourceforge.net/p/sdcc/discussion/"><i>Forum</i></a><br />
  </div>
  <br />
  <b><a href="https://sourceforge.net/p/sdcc/wiki/"><i>SDCC Wiki</i></a></b><br />
  <br />
  <b><a href="/links.php"><i>Links and More!</i></a></b><br />
  <br />
  <b><a href="https://www.openhub.net/p/small_device_c_compiler"><i>SDCC metrics by Open Hub</i></a></b><br />
  <script type='text/javascript' language='JavaScript' src='http://www.ohloh.net/projects/425;badge_js'></script><br />
</div>
